# Nomes das empresas
nome = [
    'Ecoponto Setor G', 
    'Ecoponto Tiradentes', 
    'Ecoponto São Nicolau',
    'Ecoponto Parque Boturussu',
    'Ecoponto Brasilândia',
    'Ecoponto Bandeirantes',
    'Ecoponto Vila Rica',
    'Ecoponto Guaiaponto',
    'Ecoponto Santa Cruz',
    'Ecoponto Vila das Mercês',
    'Ecoponto Ipiranga',
    'Ecoponto Itaim Paulista',
    'Ecoponto Mãe Preta',
    'Ecoponto Pesqueiro',
    'Ecoponto Flamingo',
    'Ecoponto Guarani',
    'Ecoponto Oswaldo Valle Cordeiro',
    'Ecoponto Cidade Líder',
    'Ecoponto Parque do Carmo',
    'Ecoponto Corinthians',
    'Ecoponto Imigrantes',
    'Ecoponto Jabaquara',
    'Ecoponto Lapa',
    'Ecoponto Vila Jaguará',
    'Ecoponto Bresser',
    'Ecoponto Tatuapé',
    'Ecoponto Brás',
    'Ecoponto Penha',
    'Ecoponto Berrini',
    'Ecoponto / Ponto Verde',
    'Ecoponto Jardim Eulina',
    'Ecoponto Vila União',
    'Ecoponto Parque Itajaí',
    'Ecoponto Vida Nova',
    'Ecoponto São Gabriel',
    'Ecoponto São Jorge',
    'Ecoponto Pacaembu',
    'Ecoponto Via Norte',
    'Ecoponto Paranapanema',

]

# Endereços
endereco = [
    'Cidade Tiradentes - Setor G - Rua Alfonso Asturaro Setor G, altura do nº 600 ', 
    'Cidade Tiradentes - Inácio Monteiro - Rua Regresso Feliz n º 1190 Esquina com Rua Cachoeira Morena',
    'Ermelino Matarazzo - Jardim São Nicolau - Rua Agreste de Itabaiana, nº 590 Esq. Rua Eduardo Kyioshi Shimuta' ,
    'Ermelino Matarazzo - Boturussu - Rua Nélio Batista Guimarães, 183',
    'Freguesia/ Brasilândia – Bandeirantes - Rua Itaiquara, nº 237 – Trav. Av. Itaberaba',
    'Freguesia/ Brasilândia - Freguesia do Ó - Rua Souza Filho defront. Nº 701',
    'Freguesia/ Brasilândia - Vila Rica - Rua Jorge Mamede da Silva, nº 196',
    'Guaianases – Guaiaponto - Rua da Passagem Funda Nº 250',
    'Ipiranga - Santa Cruzv - Rua Santa Cruz, nº 1452 (Baixo do Viaduto Santa Cruz)',
    'Ipiranga - Vila das Mercês - Rua Italva nº86',
    'Ipiranga - Comandante Taylor - Rua Comandante Taylor Nº 690 (Baixo do Viaduto Comandante Taylor) ',
    'Itaim Paulista – Moreira - Rua João Batista de Godói, nº 1164',
    'Itaim Paulista - Mãe Preta - Praça Mãe Preta com a Av. Fernando Figueiredo Lins',
    'Itaim Paulista - Pesqueiro - Rua Caiuas Nº 18 X Av. Itamerendiba ',
    'Itaim Paulista – Flamingo - Rua Alexandre Dias Nogueira nº353 ',
    'Itaquera - Parque Guarani - Rua Manuel Alves da Rocha, nº 584',
    'Itaquera - Oswaldo Valle Cordeiro - Av. Osvaldo Valle Cordeiro, altura do nº 420',
    'Itaquera - Cidade Líder - Rua Francesco Melzi n.º 200',
    'Itaquera - Parque do Carmo - Rua Machado Nunes Nº 95',
    'Itaquera – Corinthians - Rua Ana Perena Nº 155 (Distrito José Bonifácio) ',
    'Jabaquara – Imigrantes - Rua Opixe S/Nº com Rua Frederico Hoeme',
    'Jabaquara - Jabaquara - Rua Genaro de Carvalho x Rua Jupatis',
    'Lapa - Viaduto Antártica - Av. Antártica x Rua Gustav Willi Borghoff (Baixo do Viaduto Antártica)',
    'Lapa - Vila Jaguará - Rua Agrestina X Av. Marginal Direita do Tietê',
    'Mooca - Bresser - Pça. Giuseppe Cesari, n° 54 (Baixo do Viaduto Bresser)',
    'Mooca- Tatuapé - Av. Salim Farah Maluf, n°179 (Central de Triagem)',
    'Mooca – Brás - Av. Pires do Rio X Rua Bresser (Baixo do Viaduto Bresser) ',
    'Penha - Penha I - Rua Dr. Heládio, nº 104',
    'Pinheiros - Pinheiros - Praça. do Cancioneiro, nº 15 (Baixo da Ponte Eng. Ary Torres)  ',
    'Barão Geraldo - Av. Santa Isabel, s/nº',
    'Jardim Eulina - Avenida Marechal Rondon esq. Rua José Manuel Veiga',
    'Vila União - Rua Manoel Gomes Ferreira, esq. Rua Jose Ramos Catarino',
    'Parque Itajaí - Rua Celso Soares Couto, s/n',
    'Vida Nova - Rua Góia Jr. s/n',
    'Jardim São Gabriel - Rua Jose Martins Lourenço, esq. Rua Geraldo Bretas',
    'Parque São Jorge - Rua Plácida Pretini, s/n',
    'Jardim Pacaembu - Rua Dante Suriane esq. com Av. Padre Gaspar Bertoni',
    'Parque Via Norte - Rua dos Cambarás, 200',
    'Jardim Paranapanema - Rua Serra d’água Esq. Rua Felismina Stemmer Cajado'

]

# Latidute de cada empresa
latitude = [
    -23.586250,
    -23.573333,
    -23.522972,
    -23.503750,
    -23.486278,
    -23.505750,
    -23.469797,
    -23.555194,
    -23.599710,
    -23.623652,
    -23.600250,
    -23.497493,
    -23.509780,
    -23.501105,
    -23.514389,
    -23.520778,
    -23.556534,
    -23.562806,
    -23.578833,
    -23.547716,
    -23.632306,
    -23.653250,
    -23.524395,
    -23.516473,
    -23.544348,
    -23.529889,
    -23.547425,
    -23.531281,
    -23.597793,
    -22.817167,
    -22.891670,
    -22.936077,
    -22.961694,
    -22.977306,
    -22.942204,
    -22.896039,
    -22.904601,
    -22.885797,
    -22.915936

]
# Longitude de cada empresa
longitude = [
    -46.396417,
    -46.401500,
    -46.482750,
    -46.485139,
    -46.695139,
    -46.704556,
    -46.674872,
    -46.412981,
    -46.623174,
    -46.605254,
    -46.597167,
    -46.370850,
    -46.416869,
    -46.389421,
    -46.421194,
    -46.463583,
    -46.491327,
    -46.497306,
    -46.486583,
    -46.436929,
    -46.630694,
    -46.649444,
    -46.670643,
    -46.742042,
    -46.606055,
    -46.583000,
    -46.602720,
    -46.525451,
    -46.691312,
    -47.100583,
    -47.101041,
    -47.118067,
    -47.189528,
    -47.177861,
    -47.156328,
    -47.105494,
    -47.128179,
    -47.037482

]
# Tipo de materiais
material = [
    ['papel/papelão', 'plástico', 'vidro', 'lixo eletronico'],
    ['metal', 'papel/papelão', 'lixo eletronico', 'vidro'],
    ['papel', 'garrafa', 'papelão','lixo eletronico'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, lixo eletronico, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico ,lixo eletronico, vidro, metal'],
    ['papel/papelão, lixo eletronico, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, lixo eletronico, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['lixo eletronico, papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, lixo eletronico, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['lixos orgânicos, papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, lixo eletronico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, lixo eletronico, plástico, vidro, metal'],
    ['papel/papelão, lixo eletronico, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, lixo eletronico, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, plástico, vidro, metal'],
    ['papel/papelão, lixo eletronico, plástico, vidro, metal']


]